name: "UrlShortener"

services:
  urlshortener:
    image: url-shortener-api
    container_name: urlshortener
    build:
      context: .
      dockerfile: src/UrlShortener.Api/Dockerfile
    ports:
        - "8080:80"
        - "4443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ConnectionStrings__UrlShortenerDb=Host=postgre-db;Port=5432;Database=urlshortener;Username=urlshortener;Password=urlshortener
    depends_on:
      - postgre-db
    networks:
      - app-network

  urlshortener-web:
    image: url-shortener-web
    container_name: urlshortener-web
    build:
      context: .
      dockerfile: web/UrlShortener/Dockerfile
    ports:
        - "8081:81"
        - "4444:444"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=81
      - ASPNETCORE_HTTPS_PORTS=444
      - UrlShortenerApi__Url=https://urlshortener:443
    depends_on:
      - urlshortener
    networks:
      - app-network

  postgre-db:
    container_name: postgre-db
    image: postgres:latest
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener
    volumes:
       - postgrevolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network


volumes:
    postgrevolume:

networks:
  app-network:
    driver: bridge
